In [23]:
#Q1
import pandas as pd
import numpy as np
print(pd.__version__)

3.0.6

In [2]:
data=pd.read_csv("car_fuel_efficiency_2026.csv")

In [6]:
#Q2
len(data)

10000

In [4]:
data.head(5)

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
#Q3
data['fuel_type'].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [7]:
#Q4
data.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [3]:
#Q5
data.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [45]:
#The question in assignment is for overall but on github the homework only says for Asia. So just producing answers for both in notebook. 
#The answers are same in both case
data['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [44]:
#For Asia
data[data['origin']=='Asia']['fuel_efficiency_mpg'].max()

np.float64(41.2)

In [8]:
#Q6
data['horsepower'].median()

np.float64(254.0)

In [9]:
data['horsepower'].mode()

0    252.0
Name: horsepower, dtype: float64

In [10]:
data['horsepower'].fillna(data['horsepower'].mode())

0       243.0
1       272.0
2       267.0
3       258.0
4       304.0
        ...
9995    271.0
9996    244.0
9997    267.0
9998    270.0
9999    295.0
Name: horsepower, Length: 10000, dtype: float64

In [11]:
len(data['horsepower'])

10000

In [12]:
data['horsepower'].median()

np.float64(254.0)

In [14]:
#Q7
cars_asia=data[data['origin']=='Asia']

In [24]:
cols=['vehicle_weight','model_year']
X=np.array(cars_asia[cols][:7])

In [25]:
X

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [33]:
XTX=X.T@X
XTX

array([[131950500,  60750580],
       [ 60750580,  28041424]])

In [34]:
inverted_XTX=np.linalg.inv(XTX)

In [36]:
y=[1100, 1300, 800, 900, 1000, 1100, 1200]

In [39]:
w=(inverted_XTX@X.T)@y

In [40]:
w

array([0.13644777, 0.2327492 ])

In [41]:
sum(w)

np.float64(0.36919696904925486)